title: "Barney Pinkerton"
email: ""
description: ""
minimal_mistakes_skin: default
search: false

# Social handles
twitter_username: ""
github_username: "barneypinkerton"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
timezone: ""

# Remove pagination completely to FIX “Page 2” title bug
paginate: null
paginate_path: null

include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Author profile (used in footer + optional profile boxes)
author:
  name   : "Barney Pinkerton"
  avatar : "/assets/images/bio-pic.png"
  bio    : "Music Business & Music Tech @NYU"

# Footer icons
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:barneyjpinkerton@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/barney-p-49b439178"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/barneypinkerton"

# Default layouts for posts + pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# Tag + category pages
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Projects collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Tab image 
favicon: /assets/images/bio-pic.png
